### ISSUE TITLE
Missing specializations

### ISSUE THREAD

**Issue by Ericgig** [qutip/qutip-jax#5]
Yet to add specialization:

- [x] properties, measurement: `isherm`, `isdiag`, `iszero`, `expect`, `inner`, `norm` (#8)
- [x] linalg: `eigs`, (#10)
- [x] `svd`, `solve` (#16)
- [x] Array manipulation: `ptrace`, `reshape`, `column_stack`, (#9)
- [x] Permute: `dimensions`, `indices` (#11)

Skipped specialization:
- `logm`: not available in jax.
- `imul`, `iadd`: We may want to remove inplace operation from qutip.
- `tidyup`: Only meaningful for sparse array
